; ================================================
; IGI EDITOR CONFIGURATION
; ================================================

[GamePath]
; The root directory of your Project IGI installation.
IGIPath=D:\IGI1
Level=1
EditorPath=.
QEditorPath=C:\Users\hasee\AppData\Roaming\QEditor

[Paths]
AIFiles=C:\Users\hasee\AppData\Roaming\QEditor\AIFiles
QCompiler=C:\Users\hasee\AppData\Roaming\QEditor\QCompiler
QFiles=C:\Users\hasee\AppData\Roaming\QEditor\QFiles
QGraphs=C:\Users\hasee\AppData\Roaming\QEditor\QGraphs

[Marker]
; ------------------------------------------------
; IGI 2 Editor-style object manipulation bindings
; ------------------------------------------------

; Base manipulation
Manipulate=LeftMouseButton

; Position manipulation
ManipulatePositionXY=Shift
ManipulatePositionXZ=Ctrl
ManipulatePositionXZAlt=Shift+Ctrl

; Snap functions
ManipulatePositionSnapToGround=S
ManipulatePositionSnapToObject=O

; Orientation manipulation
ManipulateOrientationAlpha=A
ManipulateOrientationBeta=B
ManipulateOrientationGamma=G
ManipulateOrientationReset=Space

; Utility Shortcuts
TeleportToMarker=F11
ResetMarkerToPlayer=H
